apiVersion: v1
kind: Service
metadata:
  name: ec2app-service
spec:
  selector:
    app: ec2app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110